// cs-frontier-hub/web/src/components/FavButton.vue
<script setup>
import { ref } from 'vue'
import Icon from './Icon.vue'
import { api } from '../lib/api'

const props = defineProps({
  itemId: { type: Number, required: true },
  favorited: { type: Boolean, default: false },
})
const emit = defineEmits(['update'])

const active = ref(props.favorited)
const busy = ref(false)

async function toggle() {
  if (busy.value) return
  busy.value = true
  try {
    const r = await api.toggleFav(props.itemId)
    active.value = r.favorited
    emit('update', active.value)
  } catch (e) {
    console.error(e)
  } finally {
    busy.value = false
  }
}
</script>

<template>
  <button
    class="btn !px-2.5 !py-2 transition-colors"
    :class="active ? 'text-rose-500' : 'btn-ghost text-muted hover:text-rose-500'"
    :title="active ? '取消收藏' : '收藏'"
    @click.stop="toggle"
  >
    <Icon :name="'heart'" :size="18" :fill="active ? 'currentColor' : 'none'" />
  </button>
</template>

// cs-frontier-hub/web/src/components/FavButton.tsx
import { Heart } from 'lucide-react'
import { api } from '../lib/api'
import { ensureSession } from '../lib/session'

export function FavButton({
  itemId,
  active,
  onChanged,
}: {
  itemId: number
  active: boolean
  onChanged?: (next: boolean) => void
}) {
  const handle = async (e: React.MouseEvent) => {
    e.preventDefault()
    e.stopPropagation()
    try {
      const sid = await ensureSession()
      const r = await api.toggleFavorite(sid, itemId)
      onChanged?.(r.favorited)
    } catch (err) {
      alert('收藏失败：' + (err as Error).message)
    }
  }
  return (
    <button
      onClick={handle}
      aria-label="收藏"
      className={`btn-ghost h-8 w-8 !px-0 ${active ? 'text-rose-400 border-rose-400/40' : 'text-muted'}`}
    >
      <Heart size={16} className={active ? 'fill-rose-400' : ''} />
    </button>
  )
}
