// competition-hub/web/src/components/Navbar.tsx
import { Link, useNavigate } from 'react-router-dom'
import { Radar, Compass, Heart, PlusCircle, LogOut, User as UserIcon } from 'lucide-react'
import { useAuth } from '../lib/auth'
import { useUI } from '../lib/ui'

export function Navbar() {
  const { user, logout } = useAuth()
  const { openLogin } = useUI()
  const navigate = useNavigate()

  return (
    <header className="sticky top-0 z-40 border-b border-white/10 bg-ink-950/70 backdrop-blur-xl">
      <div className="mx-auto flex h-16 max-w-6xl items-center gap-4 px-4">
        <Link to="/" className="flex items-center gap-2">
          <span className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-neon-cyan to-neon-blue text-ink-950 shadow-glow">
            <Radar size={20} />
          </span>
          <span className="text-lg font-bold tracking-tight text-white neon-text">竞赛雷达</span>
        </Link>

        <nav className="ml-2 hidden items-center gap-1 text-sm text-slate-300 md:flex">
          <Link to="/" className="rounded-lg px-3 py-2 hover:bg-white/5 hover:text-white">
            全部竞赛
          </Link>
          <Link to="/favorites" className="inline-flex items-center gap-1.5 rounded-lg px-3 py-2 hover:bg-white/5 hover:text-white">
            <Heart size={15} /> 我的收藏
          </Link>
          <Link to="/submit" className="inline-flex items-center gap-1.5 rounded-lg px-3 py-2 hover:bg-white/5 hover:text-white">
            <PlusCircle size={15} /> 发布赛事
          </Link>
        </nav>

        <div className="ml-auto flex items-center gap-2">
          {user ? (
            <div className="flex items-center gap-2">
              <span className="hidden items-center gap-1.5 rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-sm text-slate-200 sm:inline-flex">
                <UserIcon size={14} /> {user.username}
              </span>
              <button
                className="btn-ghost"
                onClick={() => {
                  logout()
                  navigate('/')
                }}
                title="退出登录"
              >
                <LogOut size={15} />
              </button>
            </div>
          ) : (
            <button className="btn-primary" onClick={openLogin}>
              <Compass size={15} /> 登录 / 注册
            </button>
          )}
        </div>
      </div>
    </header>
  )
}

// cs-frontier-hub/web/src/components/Navbar.vue
<script setup>
import { RouterLink } from 'vue-router'
import Icon from './Icon.vue'
import ThemeToggle from './ThemeToggle.vue'
</script>

<template>
  <header class="sticky top-0 z-30 glass border-b">
    <nav class="mx-auto flex max-w-6xl items-center gap-3 px-4 py-3">
      <RouterLink to="/" class="flex items-center gap-2 font-extrabold tracking-tight">
        <span class="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-accent to-accent-2 text-white shadow-glow">
          <Icon name="network" :size="20" />
        </span>
        <span class="hidden sm:block text-lg">CS 前沿<span class="neon">地图</span></span>
      </RouterLink>

      <div class="ml-auto flex items-center gap-1.5">
        <RouterLink to="/" class="chip" active-class="chip-active">
          <Icon name="rocket" :size="16" /><span class="hidden sm:inline">首页</span>
        </RouterLink>
        <RouterLink to="/favorites" class="chip" active-class="chip-active">
          <Icon name="heart" :size="16" /><span class="hidden sm:inline">收藏</span>
        </RouterLink>
        <RouterLink to="/admin" class="chip" active-class="chip-active">
          <Icon name="cpu" :size="16" /><span class="hidden sm:inline">管理</span>
        </RouterLink>
        <ThemeToggle />
      </div>
    </nav>
  </header>
</template>
