// cs-frontier-hub/web/src/views/Favorites.vue
<script setup>
import { ref, onMounted } from 'vue'
import { RouterLink } from 'vue-router'
import api from '../lib/api'
import Icon from '../components/Icon.vue'
import ItemCard from '../components/ItemCard.vue'

const items = ref([])
const loading = ref(true)

onMounted(async () => {
  try {
    items.value = await api.favorites()
  } catch (e) {
    items.value = []
  } finally {
    loading.value = false
  }
})
</script>

<template>
  <main class="mx-auto max-w-6xl px-4 pb-10">
    <h1 class="mt-8 flex items-center gap-2 text-2xl font-extrabold">
      <Icon name="heart" :size="22" class="text-rose-500" /> 我的收藏
    </h1>
    <p class="mt-1 text-sm text-muted">收藏基于本机匿名会话，清空浏览器数据会丢失。</p>

    <div v-if="loading" class="grid place-items-center py-20 text-muted">
      <Icon name="cpu" :size="28" class="float-y" />
    </div>
    <div v-else-if="items.length" class="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
      <ItemCard v-for="it in items" :key="it.id" :item="it" />
    </div>
    <div v-else class="card mt-6 place-items-center py-16 text-center text-muted">
      <Icon name="heart" :size="26" />
      <p class="mt-2">还没有收藏。去列表里点 ♥ 收藏感兴趣的前沿信息吧。</p>
      <RouterLink to="/" class="btn btn-primary mt-3"><Icon name="rocket" :size="15" /> 去逛逛</RouterLink>
    </div>
  </main>
</template>

// cs-frontier-hub/web/src/pages/Favorites.tsx
import { useEffect, useState } from 'react'
import { Bookmark, Heart } from 'lucide-react'
import { api } from '../lib/api'
import { ensureSession } from '../lib/session'
import type { Item } from '../lib/types'
import { ItemCard } from '../components/ItemCard'

export function Favorites() {
  const [items, setItems] = useState<Item[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    ensureSession()
      .then((sid) => api.getFavorites(sid))
      .then(setItems)
      .finally(() => setLoading(false))
  }, [])

  return (
    <div className="mx-auto max-w-7xl px-4 py-8">
      <h1 className="flex items-center gap-2 text-2xl font-extrabold">
        <Bookmark size={22} className="text-accent" /> 我的收藏
      </h1>
      <p className="mt-1 text-sm text-muted">收藏的前沿信息会保存在本机浏览器会话中。</p>

      <div className="mt-6">
        {loading ? (
          <div className="card py-16 text-center text-muted">加载中…</div>
        ) : items.length === 0 ? (
          <div className="card flex flex-col items-center gap-3 py-16 text-center text-muted">
            <Heart size={28} />
            <p>还没有收藏任何内容。点击卡片上的 ♥ 即可收藏。</p>
            <a href="#/" className="btn-primary mt-2">
              去发现前沿
            </a>
          </div>
        ) : (
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {items.map((i) => (
              <ItemCard key={i.id} item={i} />
            ))}
          </div>
        )}
      </div>
    </div>
  )
}
