// cs-frontier-hub/web/src/pages/Home.tsx
import { useEffect, useMemo, useState } from 'react'
import { Search, TrendingUp, Layers, Boxes, ArrowRight, Sparkles } from 'lucide-react'
import { api } from '../lib/api'
import { ensureSession, getSessionId } from '../lib/session'
import type { Category, Item, Stats } from '../lib/types'
import { Sidebar } from '../components/Sidebar'
import { ItemCard } from '../components/ItemCard'

const SORTS = [
  { v: 'latest', label: '最新' },
  { v: 'stars', label: 'Star 数' },
  { v: 'views', label: '热度' },
  { v: 'title', label: '名称' },
]

export function Home() {
  const [categories, setCategories] = useState<Category[]>([])
  const [stats, setStats] = useState<Stats | null>(null)
  const [items, setItems] = useState<Item[]>([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [loading, setLoading] = useState(false)

  const [q, setQ] = useState('')
  const [debounced, setDebounced] = useState('')
  const [category, setCategory] = useState('')
  const [sourceType, setSourceType] = useState('')
  const [sort, setSort] = useState('latest')

  const sessionId = getSessionId()

  useEffect(() => {
    api.getCategories().then(setCategories)
    api.getStats().then(setStats)
    ensureSession().catch(() => {})
  }, [])

  useEffect(() => {
    const t = setTimeout(() => setDebounced(q), 300)
    return () => clearTimeout(t)
  }, [q])

  // 任意筛选变化 -> 重置到第 1 页并重新拉取
  useEffect(() => {
    setPage(1)
  }, [debounced, category, sourceType, sort])

  useEffect(() => {
    setLoading(true)
    api
      .listItems({
        q: debounced,
        category,
        source_type: sourceType,
        sort,
        page,
        page_size: 12,
        session_id: sessionId,
      })
      .then((r) => {
        setTotal(r.total)
        setItems((prev) => (page === 1 ? r.items : [...prev, ...r.items]))
        setTotal(r.total)
      })
      .finally(() => setLoading(false))
  }, [debounced, category, sourceType, sort, page, sessionId])

  const featured = useMemo(
    () => items.filter((i) => i.featured).slice(0, 3),
    [items],
  )
  const showFeatured = !debounced && !category && !sourceType && page === 1

  return (
    <div className="mx-auto max-w-7xl px-4 py-8">
      {/* Hero */}
      <section className="relative mb-10 overflow-hidden rounded-3xl border p-8 sm:p-12">
        <div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-accent/20 blur-3xl" />
        <div className="absolute -bottom-24 -left-10 h-56 w-56 rounded-full bg-accent-2/20 blur-3xl" />
        <div className="relative">
          <span className="badge border-accent/30 bg-accent/10 text-accent">
            <Sparkles size={13} /> 前沿技术 · 实时聚合
          </span>
          <h1 className="mt-4 max-w-3xl text-3xl font-extrabold leading-tight sm:text-5xl">
            计算机 / <span className="neon">Agent · LLM · AI</span> 前沿知识聚合
          </h1>
          <p className="mt-3 max-w-2xl text-muted">
            收录 GPU 算子、Triton、推理引擎、Agent 框架、MCP、RAG、强化学习、混元 AI Infra、顶会前沿等方向，
            聚合 GitHub 高星项目、开源资料与前沿产品。
          </p>

          {/* 搜索 */}
          <div className="mt-6 flex max-w-2xl items-center gap-2 rounded-2xl border bg-surface p-2 shadow-glow">
            <Search size={18} className="ml-2 text-muted" />
            <input
              value={q}
              onChange={(e) => setQ(e.target.value)}
              placeholder="搜索项目、模型、框架、关键词，如 vLLM、MCP、DeepSeek、Triton…"
              className="flex-1 bg-transparent px-1 py-2 text-sm outline-none"
            />
            {q && (
              <button onClick={() => setQ('')} className="btn-ghost h-8 !px-3 text-xs">
                清空
              </button>
            )}
          </div>

          {/* 统计 */}
          {stats && (
            <div className="mt-6 flex flex-wrap gap-3 text-sm">
              <Stat Icon={Boxes} label="前沿条目" value={stats.total} />
              <Stat Icon={Layers} label="技术分类" value={stats.categories} />
              <Stat Icon={TrendingUp} label="趋势中" value={stats.trending} />
            </div>
          )}
        </div>
      </section>

      {/* 精选 */}
      {showFeatured && featured.length > 0 && (
        <section className="mb-8">
          <h2 className="mb-3 flex items-center gap-2 text-lg font-bold">
            <Sparkles size={18} className="text-accent" /> 编辑精选
          </h2>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {featured.map((i) => (
              <ItemCard key={i.id} item={i} />
            ))}
          </div>
        </section>
      )}

      {/* 主体：侧栏 + 列表 */}
      <div className="grid gap-6 lg:grid-cols-[260px_1fr]">
        <div className="lg:sticky lg:top-20 lg:self-start">
          <Sidebar
            categories={categories}
            activeCategory={category}
            onSelectCategory={setCategory}
            sourceType={sourceType}
            onSelectSource={setSourceType}
          />
        </div>

        <div>
          <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
            <p className="text-sm text-muted">
              共 <span className="font-semibold text-fg">{total}</span> 条结果
              {category && ' · 已筛选分类'}
              {sourceType && ' · 已筛选类型'}
              {debounced && ` · 关键词「${debounced}」`}
            </p>
            <div className="flex items-center gap-2">
              <span className="text-xs text-muted">排序</span>
              <select
                value={sort}
                onChange={(e) => setSort(e.target.value)}
                className="input !w-auto !py-1.5 text-sm"
              >
                {SORTS.map((s) => (
                  <option key={s.v} value={s.v}>
                    {s.label}
                  </option>
                ))}
              </select>
            </div>
          </div>

          {loading && page === 1 ? (
            <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
              {Array.from({ length: 6 }).map((_, i) => (
                <div key={i} className="card h-44 animate-pulse opacity-60" />
              ))}
            </div>
          ) : items.length === 0 ? (
            <div className="card flex flex-col items-center gap-2 py-16 text-center text-muted">
              <Search size={28} />
              <p>没有找到匹配的前沿信息，换个关键词试试？</p>
            </div>
          ) : (
            <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
              {items.map((i) => (
                <ItemCard key={i.id} item={i} />
              ))}
            </div>
          )}

          {/* 分页 */}
          {items.length < total && (
            <div className="mt-6 flex justify-center">
              <button className="btn-primary" disabled={loading} onClick={() => setPage((p) => p + 1)}>
                {loading ? '加载中…' : '加载更多'} <ArrowRight size={15} />
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

function Stat({ Icon, label, value }: { Icon: any; label: string; value: number }) {
  return (
    <div className="flex items-center gap-2 rounded-xl border bg-surface px-3 py-2">
      <Icon size={16} className="text-accent" />
      <span className="font-bold text-fg">{value}</span>
      <span className="text-muted">{label}</span>
    </div>
  )
}

// cs-frontier-hub/web/src/views/Home.vue
<script setup>
import { ref, onMounted, computed, watch, nextTick } from 'vue'
import api from '../lib/api'
import Icon from '../components/Icon.vue'
import TechArchitecture from '../components/TechArchitecture.vue'
import CategoryNav from '../components/CategoryNav.vue'
import ItemCard from '../components/ItemCard.vue'

const categories = ref([])
const stats = ref(null)
const items = ref([])
const total = ref(0)
const totalPages = ref(1)
const page = ref(1)
const loading = ref(false)

const q = ref('')
const selectedCategory = ref('')
const selectedSource = ref('')
const hoverSrc = ref('')
const sort = ref('latest')

const gridRef = ref(null)
const crawling = ref(false)
const crawlMsg = ref('')

const SORTS = [
  { v: 'latest', label: '最新' },
  { v: 'views', label: '最热' },
  { v: 'stars', label: '星标' },
  { v: 'title', label: '名称' },
]

const SOURCES = [
  { v: '', label: '全部', icon: 'sparkles' },
  { v: 'repo', label: '仓库', icon: 'github' },
  { v: 'paper', label: '论文', icon: 'file-text' },
  { v: 'blog', label: '博客', icon: 'book-open' },
  { v: 'news', label: '资讯', icon: 'newspaper' },
  { v: 'product', label: '产品', icon: 'box' },
]

async function loadCategories() {
  categories.value = await api.categories()
}
async function loadStats() {
  stats.value = await api.stats()
}
async function loadItems() {
  loading.value = true
  try {
    const r = await api.items({
      q: q.value, category: selectedCategory.value, source_type: selectedSource.value,
      sort: sort.value, page: page.value, page_size: 12,
    })
    items.value = r.items
    total.value = r.total
    totalPages.value = r.total_pages
  } finally {
    loading.value = false
  }
}

async function search() {
  page.value = 1
  await loadItems()
}

function onSelectCategory(slug) {
  selectedCategory.value = slug
  page.value = 1
  nextTick(() => gridRef.value?.scrollIntoView({ behavior: 'smooth', block: 'start' }))
}

async function crawl() {
  if (crawling.value) return
  crawling.value = true
  crawlMsg.value = '正在从 GitHub / Gitee / HuggingFace / arXiv / CSDN / AI 资讯 抓取最新前沿信息…'
  try {
    const r = await api.runCrawler(
      ['github', 'gitee', 'hf', 'arxiv', 'csdn', 'news', 'semantic'], 20)
    const parts = Object.entries(r.by_source || {})
      .map(([k, v]) => `${k} +${v.added}`).join('，')
    crawlMsg.value = `抓取完成：新增 ${r.added} 条（${parts}）。其中 ${r.with_images} 条带真实封面图。`
    await Promise.all([loadCategories(), loadStats(), loadItems()])
  } catch (e) {
    crawlMsg.value = '抓取失败：' + (e.message || e)
  } finally {
    crawling.value = false
  }
}

watch(selectedCategory, () => loadItems())
watch(selectedSource, () => { page.value = 1; loadItems() })
watch(sort, () => loadItems())

onMounted(async () => {
  await ensureSessionSafe()
  await Promise.all([loadCategories(), loadStats()])
  await loadItems()
})

async function ensureSessionSafe() {
  try { await api.createSession() } catch (e) { /* ignore */ }
}
</script>

<template>
  <main class="mx-auto max-w-6xl px-4 pb-10">
    <!-- Hero -->
    <section class="hero-glow relative pt-12 pb-8 text-center">
      <div class="mb-3 flex justify-center">
        <span class="kicker">FRONTIER_INTELLIGENCE_HUB</span>
      </div>
      <div class="float-y mb-4 inline-flex items-center gap-2 rounded-full border bg-surface-2 px-3 py-1 text-xs text-muted">
        <Icon name="sparkles" :size="14" class="text-accent" />
        聚合 GitHub · Gitee · 论文 · 博客 · AI 资讯 等全网前沿
      </div>
      <h1 class="text-3xl font-extrabold tracking-tight sm:text-5xl">
        CS 前沿<span class="gradient-text">知识地图</span>
      </h1>
      <p class="mx-auto mt-3 max-w-2xl text-sm text-muted sm:text-base">
        一个动态的技术架构视图 + 实时聚合的前沿信息库。点击下方架构图中的任意节点，即可按方向筛选开源项目、论文、博客与资讯。
      </p>

      <!-- 搜索 -->
      <form class="mx-auto mt-6 flex max-w-xl items-center gap-2" @submit.prevent="search">
        <div class="relative flex-1">
          <Icon name="search" :size="18" class="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-muted" />
          <input
            v-model="q" class="input !pl-10" type="text"
            placeholder="搜索项目 / 论文 / 技术，如 vLLM、Agent、量化…"
            @keyup.enter="search"
          />
        </div>
        <button class="btn btn-primary" type="submit">
          <Icon name="search" :size="16" /> 搜索
        </button>
      </form>

      <!-- 实时统计 -->
      <div v-if="stats" class="mt-6 flex flex-wrap items-center justify-center gap-3 text-sm">
        <span class="badge border-accent/30 text-accent">
          <Icon name="boxes" :size="13" /> {{ stats.total }} 条前沿信息
        </span>
        <span class="badge border-accent-2/30 text-accent-2">
          <Icon name="layers" :size="13" /> {{ stats.categories }} 个方向
        </span>
        <span class="badge border-emerald-400/30 text-emerald-500">
          <Icon name="star" :size="13" /> {{ stats.featured }} 精选
        </span>
        <button class="badge border-amber-400/30 text-amber-500 transition hover:brightness-110" @click="crawl" :disabled="crawling">
          <Icon name="rocket" :size="13" /> {{ crawling ? '抓取中…' : '抓取最新前沿' }}
        </button>
      </div>
      <p v-if="crawlMsg" class="mt-2 text-xs text-muted">{{ crawlMsg }}</p>
    </section>

    <!-- 动态技术架构图 -->
    <section class="card mt-2 overflow-hidden p-5">
      <div class="mb-3 flex items-center justify-between">
        <h2 class="flex items-center gap-2 text-lg font-bold">
          <Icon name="network" :size="18" class="text-accent" /> 动态技术架构地图
        </h2>
        <span class="text-xs text-muted">点击节点按方向筛选 ↓</span>
      </div>
      <TechArchitecture :categories="categories" @select="onSelectCategory" />
    </section>

      <!-- 筛选 + 列表 -->
    <section ref="gridRef" class="mt-8 scroll-mt-24">
      <div class="mb-4 flex flex-col gap-3">
        <!-- 来源筛选 -->
        <div class="flex flex-wrap items-center gap-2">
          <button
            v-for="s in SOURCES" :key="s.v"
            class="chip src-chip" :class="{ 'chip-active': selectedSource === s.v }"
            @click="selectedSource = s.v"
            @mouseenter="hoverSrc = s.v" @mouseleave="hoverSrc = ''"
          >
            <Icon :name="s.icon" :size="14" class="src-icon" :class="{ 'src-icon-on': selectedSource === s.v, 'src-icon-hover': hoverSrc === s.v }" />
            <span>{{ s.label }}</span>
          </button>
        </div>
        <CategoryNav :categories="categories" :active="selectedCategory" @select="onSelectCategory" />
        <div class="flex items-center justify-between">
          <p class="text-sm text-muted">
            共 <span class="font-semibold text-fg">{{ total }}</span> 条
            <span v-if="selectedCategory">· 已筛选「{{ categories.find(c => c.slug === selectedCategory)?.name }}」</span>
          </p>
          <label class="flex items-center gap-2 text-sm text-muted">
            排序
            <select v-model="sort" class="input !w-auto !py-1">
              <option v-for="s in SORTS" :key="s.v" :value="s.v">{{ s.label }}</option>
            </select>
          </label>
        </div>
      </div>

      <div v-if="loading" class="grid place-items-center py-20 text-muted">
        <Icon name="cpu" :size="28" class="float-y" />
      </div>

      <div v-else-if="items.length" class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
        <ItemCard v-for="it in items" :key="it.id" :item="it" />
      </div>
      <div v-else class="card place-items-center py-16 text-center text-muted">
        <Icon name="search" :size="26" />
        <p class="mt-2">没有找到匹配的前沿信息，换个关键词或方向试试。</p>
      </div>

      <!-- 分页 -->
      <div v-if="totalPages > 1" class="mt-6 flex items-center justify-center gap-3">
        <button class="btn btn-ghost" :disabled="page <= 1" @click="page--; loadItems()">
          <Icon name="arrow-right" :size="15" class="rotate-180" /> 上一页
        </button>
        <span class="text-sm text-muted">{{ page }} / {{ totalPages }}</span>
        <button class="btn btn-ghost" :disabled="page >= totalPages" @click="page++; loadItems()">
          下一页 <Icon name="arrow-right" :size="15" />
        </button>
      </div>
    </section>
  </main>
</template>
